steps:
  # Run tests and save to file
  - name: golang:1.18
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go install github.com/GoogleCloudPlatform/golang-samples/spanner/...
        go run main.go createdatabase projects/$GCLOUD_PROJECT/instances/test-instance/databases/example-db2